//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KütüphaneAnaMenü
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emanet
    {
        public int emanet_refno { get; set; }
        public string isim { get; set; }
        public int numara { get; set; }
        public string barkod_no { get; set; }
        public string kitap_adi { get; set; }
        public string kitap_yazari { get; set; }
        public System.DateTime baslangic_tarihi { get; set; }
        public Nullable<System.DateTime> teslim_tarihi { get; set; }
        public string hasar_durumu { get; set; }
    }
}
