//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KütüphaneAnaMenü
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap
    {
        public string barkod_id { get; set; }
        public string kitap_adi { get; set; }
        public string yazar_adi { get; set; }
        public string yayin_evi { get; set; }
        public int kitap_turu { get; set; }
        public string yayin_yili { get; set; }
        public Nullable<System.DateTime> olusturulma_tarihi { get; set; }
        public Nullable<int> stok_sayisi { get; set; }
    }
}
