//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KütüphaneAnaMenü
{
    using System;
    using System.Collections.Generic;
    
    public partial class OkuyucuBilgisi
    {
        public int Okuyucu_Refno { get; set; }
        public string Tckimlik { get; set; }
        public string Adi_Soyadi { get; set; }
        public string Sinifi { get; set; }
        public string Nosu { get; set; }
        public string Dogum_Tarihi { get; set; }
        public string Dogum_Yeri { get; set; }
        public string Telefon { get; set; }
        public string Eposta { get; set; }
        public Nullable<System.DateTime> uyelik_Tarihi { get; set; }
        public string Cinsiyet { get; set; }
        public string Adres { get; set; }
        public Nullable<int> Emanet_Sayisi { get; set; }
    }
}
