//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KütüphaneAnaMenü
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teslim
    {
        public int teslim_id { get; set; }
        public string kitap_adi { get; set; }
        public string hasar_durumu { get; set; }
        public string okuyucu { get; set; }
        public System.DateTime teslim_tarihi { get; set; }
    }
}
